import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";
import { fetcher } from "../utils/fetcher";
import { Verse } from "../interfaces/promiseBox";
import Layout from "../sections/Layout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />
    </div>
  );
};

export default Home;
